import { createAdminClient } from '@/lib/supabase/server'
import { Resend } from 'resend'
import { NextResponse } from 'next/server'
import { format, startOfMonth, endOfMonth, subMonths } from 'date-fns'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: Request) {
  try {
    const { clientId } = await req.json()
    const supabase = createAdminClient()

    // Get client info
    const { data: client } = await supabase.from('clients').select('*').eq('id', clientId).single()
    if (!client) return NextResponse.json({ error: 'Client not found' }, { status: 404 })

    // Get last month's metrics
    const lastMonth = subMonths(new Date(), 1)
    const start = format(startOfMonth(lastMonth), 'yyyy-MM-dd')
    const end = format(endOfMonth(lastMonth), 'yyyy-MM-dd')
    const monthLabel = format(lastMonth, 'MMMM yyyy')

    const { data: metrics } = await supabase
      .from('metrics_cache')
      .select('*')
      .eq('client_id', clientId)
      .gte('date', start)
      .lte('date', end)

    const totals = (metrics || []).reduce((acc: any, m: any) => ({
      spend: acc.spend + Number(m.spend || 0),
      conversions: acc.conversions + Number(m.conversions || 0),
      leads: acc.leads + Number(m.leads || 0),
      conversion_value: acc.conversion_value + Number(m.conversion_value || 0),
    }), { spend: 0, conversions: 0, leads: 0, conversion_value: 0 })

    const roas = totals.spend > 0 ? (totals.conversion_value / totals.spend).toFixed(2) : '0'
    const fmt = (n: number) => new Intl.NumberFormat('it-IT', { minimumFractionDigits: 0 }).format(Math.round(n))

    // Send email
    const { error: emailError } = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || 'reports@adsdash.com',
      to: client.email,
      subject: `📊 Your ${monthLabel} Ad Performance Report`,
      html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; background: #f4f4f4; margin: 0; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
  .header { background: #080c0f; padding: 32px; text-align: center; }
  .logo { font-size: 28px; font-weight: 900; color: white; letter-spacing: -1px; }
  .logo span { color: #00C8E0; }
  .subtitle { color: #5a7080; font-size: 13px; margin-top: 6px; }
  .body { padding: 32px; }
  .greeting { font-size: 22px; font-weight: 700; color: #1a1a2e; margin-bottom: 8px; }
  .period { color: #666; font-size: 14px; margin-bottom: 28px; }
  .kpis { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 28px; }
  .kpi { background: #f8f9fa; border-radius: 12px; padding: 20px; border-left: 4px solid #00C8E0; }
  .kpi-label { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
  .kpi-value { font-size: 26px; font-weight: 800; color: #1a1a2e; }
  .footer { background: #f8f9fa; padding: 20px 32px; text-align: center; color: #888; font-size: 12px; border-top: 1px solid #eee; }
  .btn { display: inline-block; background: #00C8E0; color: #080c0f; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-weight: 700; font-size: 14px; margin-top: 20px; }
</style></head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">Ads<span>Dash</span></div>
      <div class="subtitle">Monthly Performance Report</div>
    </div>
    <div class="body">
      <div class="greeting">Hello, ${client.name}! 👋</div>
      <div class="period">Here's your advertising performance for <strong>${monthLabel}</strong></div>
      <div class="kpis" style="display:flex;flex-wrap:wrap;gap:16px;">
        <div class="kpi" style="flex:1;min-width:120px;">
          <div class="kpi-label">💰 Total Spend</div>
          <div class="kpi-value">€${fmt(totals.spend)}</div>
        </div>
        <div class="kpi" style="flex:1;min-width:120px;">
          <div class="kpi-label">✅ Conversions</div>
          <div class="kpi-value">${fmt(totals.conversions)}</div>
        </div>
        <div class="kpi" style="flex:1;min-width:120px;">
          <div class="kpi-label">📈 ROAS</div>
          <div class="kpi-value">${roas}x</div>
        </div>
        <div class="kpi" style="flex:1;min-width:120px;">
          <div class="kpi-label">🎯 Leads</div>
          <div class="kpi-value">${fmt(totals.leads)}</div>
        </div>
      </div>
      <p style="color:#555;font-size:14px;line-height:1.6;">Log in to your dashboard to see the full breakdown by campaign, platform, and date range.</p>
      <a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard" class="btn">View Full Dashboard →</a>
    </div>
    <div class="footer">
      This report was automatically generated by AdsDash.<br>
      © ${new Date().getFullYear()} AdsDash. All rights reserved.
    </div>
  </div>
</body>
</html>`,
    })

    if (emailError) return NextResponse.json({ error: emailError.message }, { status: 500 })

    // Log the report
    await supabase.from('reports').insert({
      client_id: clientId,
      report_type: 'monthly',
      period_start: start,
      period_end: end,
      status: 'sent',
      sent_at: new Date().toISOString(),
    })

    return NextResponse.json({ success: true })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
